spring:
  application:
    name: msgsender
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        input:
          destination: wuyuexchannel
        output:
          destination: wuyuchannel
server:
  port: 20101
eureka:
  client:
    service-url:
      #将当前服务也注册到注册中心
      defaultZone: http://eurekaserver1:30001/eureka/